name: Publish KMP Library

on:
  push:  # Ejecutar en cada push a cualquier rama

jobs:
  publish:
    runs-on: macos-latest  # Necesario para generar XCFramework

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Publish to GitHub Packages (Maven)
        run: ./gradlew publish
        env:
          USERNAME_GITHUB: ${{ secrets.USER_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
